version: 2
updates:
  # Python dependencies for backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "engineering-team"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend):"
      include: "scope"

  # Python dependencies for crawler
  - package-ecosystem: "pip"
    directory: "/crawler"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "engineering-team"
    labels:
      - "dependencies"
      - "crawler"
    commit-message:
      prefix: "chore(crawler):"
      include: "scope"

  # JavaScript dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "engineering-team"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(frontend):"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(actions):"
      include: "scope"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/crawler"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "docker"