# Cloud Run service configuration for backend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: url-to-llm-backend
  annotations:
    # Use Cloud Build for automatic builds from GitHub
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Cloud SQL connections
        run.googleapis.com/cloudsql-instances: ${PROJECT_ID}:${REGION}:url-to-llm-db
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Session affinity for WebSockets
        run.googleapis.com/sessionAffinity: "true"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 900
      serviceAccountName: url-to-llm@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: gcr.io/${PROJECT_ID}/url-to-llm-backend
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: STORAGE_BACKEND
          value: "gcs"
        - name: K_SERVICE
          value: "url-to-llm-backend"
        - name: INSTANCE_CONNECTION_NAME
          value: ${PROJECT_ID}:${REGION}:url-to-llm-db
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 10