version: '3.9'

services:
  # Backend with production settings
  backend:
    restart: always
    environment:
      ENVIRONMENT: production
      DEBUG: false
    command: ["gunicorn", "app.main:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

  # Frontend with production build
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production

  # Celery worker with more concurrency
  celery-worker:
    restart: always
    environment:
      ENVIRONMENT: production
      C_FORCE_ROOT: 1
    command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info", "--concurrency=4", "--queues=crawler", "--max-tasks-per-child=100"]
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Celery beat
  celery-beat:
    restart: always
    environment:
      ENVIRONMENT: production

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

  # Remove Flower in production (use dedicated monitoring)
  flower:
    profiles:
      - monitoring