apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: url-to-llm
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: url-to-llm@PROJECT-ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT-ID/url-to-llm
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: STORAGE_BACKEND
          value: gcs
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5