name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate version format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "Invalid version format. Please use semantic versioning (e.g., v1.0.0 or v1.0.0-beta1)"
            exit 1
          fi
      
      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ inputs.version }} -m "Release ${{ inputs.version }}"
          git push origin ${{ inputs.version }}
      
      - name: Generate changelog
        id: changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: .github/cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body_path: CHANGELOG.md
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true
          files: |
            docker-compose.yml
            docker-compose.prod.yml
            README.md
            LICENSE
      
      - name: Trigger deployment workflow
        if: ${{ !inputs.prerelease }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-created
          client-payload: '{"version": "${{ inputs.version }}"}'